### ISSUE TITLE
Design: Typography 

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#106]
The Typography component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System---Gemeente-Den-Haag?node-id=3497%3A15951).
As with other components, design tokens must be added to achieve this.

We're creating a custom react component instead of wrapping the MUI Typography. Examples from Utrecht
- https://github.com/nl-design-system/utrecht/pull/43
- https://github.com/nl-design-system/utrecht/pull/49

## Acceptance Criteria

**Variants implemented**
- [x] headings
- [x] paragraphs

**Font weights** 
- [x] Default
- [x] Bold
- [x] Font weights as design token

**Requirements**
- [x] Font family can be adjusted (in our designs TheSans and TheMix are used)

**Comment by mjcarsjens** [comment]
We should have a discussion about how to deal with font sizing and actual tags used (e.g. p, h1, h2, etc.)

**Comment by ogjtech** [comment]
> We should have a discussion about how to deal with font sizing and actual tags used (e.g. p, h1, h2, etc.)

I would say keep it 1:1 to MUI's definitions. This way, should MUI ever create a new font size tag, we can just add it to the list without any faff over how to call it. This also removes confusion during implementation (if we are confused about the definition, an implementer is just not going to bother with it).

**Comment by bddjong** [comment]
We should consider looking at the Utrecht styling for this component and see if we can use it in our own components (discuss with @Robbert )
