### ISSUE TITLE
Storybook's 'show code' option displays incorrect code

### ISSUE THREAD

**Issue by DanielvanVliet** [Gemeente-DenHaag/denhaag-component-library#15]
When navigating the docs of a story on [nldsreactstorybook](http://dhreactstorybook.azurewebsites.net/), the 'show code' option does not always show working code.

For instance, in the Appbar docs: 
![show-not-working](https://user-images.githubusercontent.com/22854131/105604691-44761900-5d96-11eb-8710-9110f6a091df.PNG)

The actual story for Appbar looks like this:
```ts  
return (
    <AppBar {...args}>
      <Toolbar>
        <IconButton
          edge='start'
          className={classes.menuButton}
          color='inherit'
          aria-label='menu'
        >
          <MenuIcon />
        </IconButton>
        <Typography variant='h6'>News</Typography>
      </Toolbar>
      <Button>I am a button!</Button>
    </AppBar>
  )
```

I would expect at least working code, all of which should be in the nlds-react-components library (WithStyle is Material UI).

- [x] Investigate how to customize the code example without creating an entire .MD file.
- [x] Check all component stories to make sure `Show code` shows working code. Compile a list of all stories that have broken code examples so that follow-up issues can be made.
- [ ] Follow-up issues have been made

**Comment by ogjtech** [comment]
> https://storybook.js.org/docs/react/writing-docs/doc-blocks#docspage-1
> This documentation might help with providing custom code examples without creating an entire MD file for the docs

This indeed fixes it, shows actual raw code as it is defined in in the Storybook file. No need for follow-up issues, fixing all stories at once.
