### ISSUE TITLE
Disallow use of any type

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#152]
We configure eslint to trow an error if we use the `any` type. If we allow ourselves to use `any`, then there is really no reason to use typescript. Currently it throws a warning, but this should be changed to error.

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md

### Tasks
- [x] Configure typescript to throw error on use (`"@typescript-eslint/no-explicit-any": "error"`)
- [x] Remove all uses of `any` (36 occurrences)

**Comment by bddjong** [comment]
How many uses of any are there in the project right now? Is it a lot of work to refactor?

**Comment by GewoonMaarten** [comment]
> How many uses of any are there in the project right now? Is it a lot of work to refactor?

There are 36 occurrences of `any`. Most uses are from the `value` property which can be changed to `string | number` and properties which take a function. Most of these can be changed to (`event: ChangeEvent<Element> -> void`), see [React Typescript Events](https://felixgerschau.com/react-typescript-events/).
