### ISSUE TITLE
Going public with components repo

### ISSUE THREAD

**Issue by joostvanviegen** [Gemeente-DenHaag/denhaag-component-library#32]
Before we can go public we will need to take care of and / or check the following things. These things need to be in the master branch before going public:

- [x] The LICENSE file contains the EUPL v1.2 and copyright statement
- [x] The goal of the codebase has been documented:, what do we hope to achieve with the code [see here](https://standard.publiccode.net/criteria/document-objectives.html)
- [x] There is a link to our public issue tracker from the README file
- [x] The repository contains an up-to date CONTRIBUTING file with information on how to contribute to the codebase
- [x] The repository has been renamed to denhaag-component-library
- [x] Add information about contributions which will be included in nlds to README and CONTRIBUTING
- [x] Remove all packages from Github packages
- [ ] Publish all packages to NPM registry (give @GewoonMaarten your npm username so he can add you)
- [ ] Align package versions. Some packages have a different version number.

**Comment by Robbert** [comment]
The Den Haag component library has gone public!

@GewoonMaarten @joostvanviegen @ogjtech @DanielvanVliet and the rest... congratulations everyone! I'm proud of all your hard work! 🥳
