### ISSUE TITLE
Design: Cards/case

### ISSUE THREAD

**Issue by GewoonMaarten** [Gemeente-DenHaag/denhaag-component-library#79]
The Cards/case component needs to be styled according to the [Figma design](https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn/Design-System-Gemeente-Den-Haag?node-id=1696%3A16).

# Acceptance criteria
**States implemented**
- [x]  Normal
- [x] Hover (animation is out of scope)
- [x] Focus

**Text Support**
- [x] A title can be provided
- [x] A subtitle can be provided
- [x] A date can be provided

**Icon Support**
- [x] Card can have an arrow icon to show that the card can be opened for more details

**Requirements**
- [x] Classes use the [BEM naming convention](http://getbem.com/)
- [x] Design tokens are identified > proposed > implemented
- [x] Only the props and possible values for these props which are necessary in our use-case are exposed. All other Material-UI and standard HTML props which are not deemed necessary in our use-case should not be allowed/forwarded to the underlying component.
- [x] This component should be build of a base card

**Comment by GewoonMaarten** [comment]
Waiting for response of @fabianvalkenberg about animations. See https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn?node-id=1696:16#71589954

**Comment by bddjong** [comment]
> Waiting for response of @fabianvalkenberg about animations. See https://www.figma.com/file/JpoY3waVoQGlLQzQXTL9nn?node-id=1696:16#71589954

Animation of the hover state is out of scope for now
